from typing import Dict, Any

STYLE_PRESETS: Dict[str, Dict[str, Any]] = {
    "Hormozi": {
        "name": "Hormozi Yellow",
        "description": "Bold white punch with electric yellow active pop scale (Alex Hormozi style).",
        "font_family": "Montserrat",
        "font_size": 48,
        "font_weight": "extra-bold",
        "text_color": "#FFFFFF",
        "uppercase": True,
        "alignment": "center",
        "position": "center",
        "vertical_offset": 0,
        "highlight_color": "#FFE600",  # Punchy Hormozi Yellow
        "highlight_style": "scale",
        "highlight_bg_color": "#000000",
        "animation": "hormozi",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.0,
        "outline_color": "#000000",
        "outline_width": 3,
        "shadow_color": "rgba(0, 0, 0, 0.9)",
        "shadow_blur": 6,
        "shadow_offset_x": 2,
        "shadow_offset_y": 3,
        "letter_spacing": 1,
        "line_height": 1.2,
        "max_words_per_line": 3
    },
    "MrBeast": {
        "name": "MrBeast Pop",
        "description": "High-impact comic font, 4px heavy black stroke, bouncy pop highlight.",
        "font_family": "Komika Axis",
        "font_size": 52,
        "font_weight": "extra-bold",
        "text_color": "#FFFFFF",
        "uppercase": True,
        "alignment": "center",
        "position": "center",
        "vertical_offset": 0,
        "highlight_color": "#38EF7D",  # MrBeast Lime Green
        "highlight_style": "pop",
        "highlight_bg_color": "#E11D48",
        "animation": "pop",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.0,
        "outline_color": "#000000",
        "outline_width": 4,
        "shadow_color": "rgba(0, 0, 0, 0.95)",
        "shadow_blur": 8,
        "shadow_offset_x": 3,
        "shadow_offset_y": 3,
        "letter_spacing": 1,
        "line_height": 1.2,
        "max_words_per_line": 3
    },
    "NeonGlow": {
        "name": "Neon Glow",
        "description": "Vibrant cyan cyber glow with soft blur aura for night and tech reels.",
        "font_family": "Montserrat",
        "font_size": 46,
        "font_weight": "bold",
        "text_color": "#E0F7FA",
        "uppercase": True,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 14,
        "highlight_color": "#00F0FF",  # Electric Neon Cyan
        "highlight_style": "glow",
        "highlight_bg_color": "#0891B2",
        "animation": "glow",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.0,
        "outline_color": "#002B36",
        "outline_width": 2,
        "shadow_color": "rgba(0, 240, 255, 0.7)",
        "shadow_blur": 12,
        "shadow_offset_x": 0,
        "shadow_offset_y": 0,
        "letter_spacing": 1,
        "line_height": 1.25,
        "max_words_per_line": 4
    },
    "DesiClean": {
        "name": "Desi Clean",
        "description": "Perfect ligature support for Hindi & Gujarati with elegant background pill.",
        "font_family": "Poppins",
        "font_size": 42,
        "font_weight": "bold",
        "text_color": "#FFFFFF",
        "uppercase": False,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 14,
        "highlight_color": "#F59E0B",  # Warm Saffron Amber
        "highlight_style": "color",
        "highlight_bg_color": "#18181B",
        "animation": "smooth",
        "background_style": "box",
        "background_color": "#09090B",
        "background_opacity": 0.75,
        "outline_color": "#000000",
        "outline_width": 0,
        "shadow_color": "rgba(0, 0, 0, 0.5)",
        "shadow_blur": 4,
        "shadow_offset_x": 0,
        "shadow_offset_y": 2,
        "letter_spacing": 0,
        "line_height": 1.3,
        "max_words_per_line": 4
    },
    "Karaoke": {
        "name": "Karaoke Fill",
        "description": "Live word-by-word progressive color fill matching speaker cadence.",
        "font_family": "Montserrat",
        "font_size": 46,
        "font_weight": "extra-bold",
        "text_color": "#94A3B8",  # Unsung words soft slate
        "uppercase": True,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 15,
        "highlight_color": "#38BDF8",  # Sung words bright Sky Blue
        "highlight_style": "karaoke",
        "highlight_bg_color": "#0284C7",
        "animation": "karaoke",
        "background_style": "rounded_box",
        "background_color": "#0F172A",
        "background_opacity": 0.7,
        "outline_color": "#000000",
        "outline_width": 2,
        "shadow_color": "rgba(0, 0, 0, 0.8)",
        "shadow_blur": 6,
        "shadow_offset_x": 1,
        "shadow_offset_y": 2,
        "letter_spacing": 1,
        "line_height": 1.25,
        "max_words_per_line": 4
    },
    # Legacy fallbacks
    "Modern": {
        "name": "Modern",
        "description": "White bold text, subtle shadow, and clean active-word highlight.",
        "font_family": "Inter",
        "font_size": 44,
        "font_weight": "bold",
        "text_color": "#FFFFFF",
        "uppercase": False,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 14,
        "highlight_color": "#38BDF8",
        "highlight_style": "color",
        "highlight_bg_color": "#0284C7",
        "animation": "smooth",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.4,
        "outline_color": "#0F172A",
        "outline_width": 2,
        "shadow_color": "rgba(0, 0, 0, 0.7)",
        "shadow_blur": 6,
        "shadow_offset_x": 0,
        "shadow_offset_y": 3,
        "letter_spacing": 0,
        "line_height": 1.25,
        "max_words_per_line": 4
    },
    "Viral": {
        "name": "Viral",
        "description": "Large bold captions, punchy active-word bounce, and vibrant pill highlight.",
        "font_family": "Montserrat",
        "font_size": 52,
        "font_weight": "extra-bold",
        "text_color": "#FFFFFF",
        "uppercase": True,
        "alignment": "center",
        "position": "center",
        "vertical_offset": 0,
        "highlight_color": "#FFE600",
        "highlight_style": "scale",
        "highlight_bg_color": "#E11D48",
        "animation": "hormozi",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.0,
        "outline_color": "#000000",
        "outline_width": 3,
        "shadow_color": "rgba(0, 0, 0, 0.9)",
        "shadow_blur": 6,
        "shadow_offset_x": 2,
        "shadow_offset_y": 3,
        "letter_spacing": 1,
        "line_height": 1.2,
        "max_words_per_line": 3
    },
    "Minimal": {
        "name": "Minimal",
        "description": "Simple understated typography, soft focus, and quiet elegance.",
        "font_family": "Inter",
        "font_size": 36,
        "font_weight": "normal",
        "text_color": "#F8FAFC",
        "uppercase": False,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 12,
        "highlight_color": "#CBD5E1",
        "highlight_style": "color",
        "highlight_bg_color": "#334155",
        "animation": "none",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.0,
        "outline_color": "#000000",
        "outline_width": 0,
        "shadow_color": "rgba(0, 0, 0, 0.4)",
        "shadow_blur": 4,
        "shadow_offset_x": 0,
        "shadow_offset_y": 2,
        "letter_spacing": 0,
        "line_height": 1.3,
        "max_words_per_line": 5
    },
    "Cinematic": {
        "name": "Cinematic",
        "description": "Elegant typography, warm golden glow, and smooth transitions.",
        "font_family": "Georgia",
        "font_size": 40,
        "font_weight": "bold",
        "text_color": "#FEF3C7",
        "uppercase": False,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 16,
        "highlight_color": "#F59E0B",
        "highlight_style": "glow",
        "highlight_bg_color": "#78350F",
        "animation": "smooth",
        "background_style": "none",
        "background_color": "#000000",
        "background_opacity": 0.0,
        "outline_color": "#451A03",
        "outline_width": 2,
        "shadow_color": "rgba(245, 158, 11, 0.4)",
        "shadow_blur": 12,
        "shadow_offset_x": 0,
        "shadow_offset_y": 2,
        "letter_spacing": 1,
        "line_height": 1.3,
        "max_words_per_line": 4
    },
    "Bold": {
        "name": "Bold",
        "description": "Heavy high-contrast typography with maximum readability.",
        "font_family": "Montserrat",
        "font_size": 48,
        "font_weight": "extra-bold",
        "text_color": "#FFFFFF",
        "uppercase": True,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 15,
        "highlight_color": "#4ADE80",
        "highlight_style": "scale",
        "highlight_bg_color": "#15803D",
        "animation": "bounce",
        "background_style": "box",
        "background_color": "#000000",
        "background_opacity": 0.75,
        "outline_color": "#000000",
        "outline_width": 3,
        "shadow_color": "rgba(0, 0, 0, 0.8)",
        "shadow_blur": 6,
        "shadow_offset_x": 2,
        "shadow_offset_y": 2,
        "letter_spacing": 1,
        "line_height": 1.2,
        "max_words_per_line": 3
    },
    "Clean": {
        "name": "Clean",
        "description": "Simple professional captions with subtle active-word underline.",
        "font_family": "Inter",
        "font_size": 38,
        "font_weight": "bold",
        "text_color": "#FFFFFF",
        "uppercase": False,
        "alignment": "center",
        "position": "bottom",
        "vertical_offset": 12,
        "highlight_color": "#60A5FA",
        "highlight_style": "underline",
        "highlight_bg_color": "#1E3A8A",
        "animation": "smooth",
        "background_style": "rounded_box",
        "background_color": "#111827",
        "background_opacity": 0.6,
        "outline_color": "#000000",
        "outline_width": 1,
        "shadow_color": "rgba(0, 0, 0, 0.5)",
        "shadow_blur": 4,
        "shadow_offset_x": 0,
        "shadow_offset_y": 2,
        "letter_spacing": 0,
        "line_height": 1.25,
        "max_words_per_line": 4
    }
}

def get_style_preset(name: str) -> Dict[str, Any]:
    return STYLE_PRESETS.get(name, STYLE_PRESETS["Hormozi"])
