from typing import List, Dict, Any

DEFAULT_TEMPLATES: List[Dict[str, Any]] = [
    {
        "id": "tpl-tiktok-viral",
        "name": "TikTok Viral",
        "category": "Trending",
        "description": "Fast-paced, bold uppercase text with high contrast for short-form video.",
        "preview_text": "HOOK YOUR AUDIENCE NOW",
        "style_config": {
            "font_family": "Impact",
            "font_size": 52,
            "font_weight": "extra-bold",
            "text_color": "#FFFFFF",
            "uppercase": True,
            "alignment": "center",
            "position": "center",
            "vertical_offset": 0,
            "highlight_color": "#FACC15",
            "highlight_style": "box",
            "highlight_bg_color": "#DC2626",
            "animation": "pop",
            "background_style": "none",
            "background_color": "#000000",
            "background_opacity": 0.0,
            "outline_color": "#000000",
            "outline_width": 4,
            "shadow_color": "rgba(0,0,0,0.9)",
            "shadow_blur": 6,
            "shadow_offset_x": 2,
            "shadow_offset_y": 2,
            "letter_spacing": 1,
            "line_height": 1.2,
            "max_words_per_line": 3
        }
    },
    {
        "id": "tpl-podcast-flow",
        "name": "Podcast Story",
        "category": "Podcast",
        "description": "Subtle, conversational subtitle bar built for interviews and long discussions.",
        "preview_text": "The greatest lesson I learned was patience.",
        "style_config": {
            "font_family": "Inter",
            "font_size": 38,
            "font_weight": "bold",
            "text_color": "#FFFFFF",
            "uppercase": False,
            "alignment": "center",
            "position": "bottom",
            "vertical_offset": 14,
            "highlight_color": "#38BDF8",
            "highlight_style": "color",
            "highlight_bg_color": "#0369A1",
            "animation": "smooth",
            "background_style": "rounded_box",
            "background_color": "#0F172A",
            "background_opacity": 0.7,
            "outline_color": "#000000",
            "outline_width": 1,
            "shadow_color": "rgba(0,0,0,0.4)",
            "shadow_blur": 4,
            "shadow_offset_x": 0,
            "shadow_offset_y": 2,
            "letter_spacing": 0,
            "line_height": 1.25,
            "max_words_per_line": 5
        }
    },
    {
        "id": "tpl-motivational-pulse",
        "name": "Iron Discipline",
        "category": "Motivational",
        "description": "Inspiring, heavy typography with emerald accent pop.",
        "preview_text": "DISCIPLINE OUTLASTS MOTIVATION",
        "style_config": {
            "font_family": "Montserrat",
            "font_size": 48,
            "font_weight": "extra-bold",
            "text_color": "#FFFFFF",
            "uppercase": True,
            "alignment": "center",
            "position": "bottom",
            "vertical_offset": 18,
            "highlight_color": "#22C55E",
            "highlight_style": "scale",
            "highlight_bg_color": "#14532D",
            "animation": "bounce",
            "background_style": "box",
            "background_color": "#000000",
            "background_opacity": 0.8,
            "outline_color": "#000000",
            "outline_width": 3,
            "shadow_color": "rgba(0,0,0,0.9)",
            "shadow_blur": 8,
            "shadow_offset_x": 0,
            "shadow_offset_y": 4,
            "letter_spacing": 1,
            "line_height": 1.2,
            "max_words_per_line": 3
        }
    },
    {
        "id": "tpl-gaming-neon",
        "name": "Cyber Twitch",
        "category": "Gaming",
        "description": "Electric cyber neon styling for gaming highlights and streams.",
        "preview_text": "UNBELIEVABLE CLUTCH PLAY",
        "style_config": {
            "font_family": "Impact",
            "font_size": 46,
            "font_weight": "extra-bold",
            "text_color": "#E0E7FF",
            "uppercase": True,
            "alignment": "center",
            "position": "bottom",
            "vertical_offset": 14,
            "highlight_color": "#A855F7",
            "highlight_style": "glow",
            "highlight_bg_color": "#581C87",
            "animation": "pop",
            "background_style": "none",
            "background_color": "#000000",
            "background_opacity": 0.0,
            "outline_color": "#1E1B4B",
            "outline_width": 3,
            "shadow_color": "rgba(168, 85, 247, 0.8)",
            "shadow_blur": 14,
            "shadow_offset_x": 0,
            "shadow_offset_y": 0,
            "letter_spacing": 1,
            "line_height": 1.2,
            "max_words_per_line": 3
        }
    },
    {
        "id": "tpl-cinema-elegance",
        "name": "Cinema Gold",
        "category": "Cinematic",
        "description": "Atmospheric serif text with soft golden haze for documentaries and films.",
        "preview_text": "In the silence of the mountains.",
        "style_config": {
            "font_family": "Georgia",
            "font_size": 40,
            "font_weight": "bold",
            "text_color": "#FEF3C7",
            "uppercase": False,
            "alignment": "center",
            "position": "bottom",
            "vertical_offset": 16,
            "highlight_color": "#F59E0B",
            "highlight_style": "glow",
            "highlight_bg_color": "#78350F",
            "animation": "smooth",
            "background_style": "none",
            "background_color": "#000000",
            "background_opacity": 0.0,
            "outline_color": "#451A03",
            "outline_width": 2,
            "shadow_color": "rgba(245, 158, 11, 0.5)",
            "shadow_blur": 10,
            "shadow_offset_x": 0,
            "shadow_offset_y": 2,
            "letter_spacing": 1,
            "line_height": 1.3,
            "max_words_per_line": 4
        }
    },
    {
        "id": "tpl-business-minimal",
        "name": "Executive Clean",
        "category": "Business",
        "description": "Refined sans-serif for product demos, B2B SaaS, and keynote clips.",
        "preview_text": "Accelerate your team workflow.",
        "style_config": {
            "font_family": "Inter",
            "font_size": 36,
            "font_weight": "bold",
            "text_color": "#FFFFFF",
            "uppercase": False,
            "alignment": "center",
            "position": "bottom",
            "vertical_offset": 12,
            "highlight_color": "#6366F1",
            "highlight_style": "underline",
            "highlight_bg_color": "#312E81",
            "animation": "smooth",
            "background_style": "rounded_box",
            "background_color": "#1E293B",
            "background_opacity": 0.8,
            "outline_color": "#000000",
            "outline_width": 1,
            "shadow_color": "rgba(0,0,0,0.5)",
            "shadow_blur": 4,
            "shadow_offset_x": 0,
            "shadow_offset_y": 2,
            "letter_spacing": 0,
            "line_height": 1.25,
            "max_words_per_line": 4
        }
    }
]

